### ISSUE TITLE
Windows10 Left Autohide Tasckbar overlaps the Start Menu

### ISSUE THREAD

**Issue by mwoz** [valinet/ExplorerPatcher#2744]
When Windows10 Tasckbar is "left" and "autohide", Start Menu is partially hidden under it
![изображение_2024-01-24_215015361](https://github.com/valinet/ExplorerPatcher/assets/5764264/0bd46bf4-3c8d-46a6-850f-3864d3417643)
(In original Windows10 Start Menu is situated with slight indent)

**Comment by Amrsatrio** [comment]
Can confirm. 22621.3007. As a workaround you can enable centered start menu, it doesn't happen with it.

**Comment by shaggy2626** [comment]
im having same issue, the start menu is not panned correctly to go over the taskbar with auto hide 
![image](https://github.com/valinet/ExplorerPatcher/assets/120447538/a41a253d-27f7-4639-8194-7df082aee66b)

**Comment by pyrates999** [comment]
> im having same issue, the start menu is not panned correctly to go over the taskbar with auto hide ![image](https://private-user-images.githubusercontent.com/120447538/301338249-a41a253d-27f7-4639-8194-7df082aee66b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODU0NjQsIm5iZiI6MTcwNjc4NTE2NCwicGF0aCI6Ii8xMjA0NDc1MzgvMzAxMzM4MjQ5LWE0MWEyNTNkLTI3ZjctNDYzOS04MTk0LTdkZjA4MmFlZTY2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMDU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDQ0ZTlhMTIyZDgzN2ExY2E1NGYzNzY1NmI2OGY3ZmE3MTU4NjUzOTJkNDI5Nzg4ZGYzMmE0OGUxNzBlZjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AhIMD5A05TogOFicaKYF2snALKjNDVcAmgvwb-ea-PA)

Please include your windows version and build and EP version when you are saying it is also happening to you.

**Comment by Vipin2003** [comment]
Not Reproduced on my side...Latest PR with22631.3085
I think it is fixed in latest PR

**Comment by Wikeolf** [comment]
ExplorerPatcher Ver 22621.3880.66.6
Windows11 Ver 23H2 22631.3880
The first time I open the start menu after restarting Explorer, the start menu displays normally for a while, then gets obscured by the taskbar, and then every time I open the start menu after that, it gets obscured.

**Comment by pyrates999** [comment]
> ExplorerPatcher Ver 22621.3880.66.6 Windows11 Ver 23H2 22631.3880 The first time I open the start menu after restarting Explorer, the start menu displays normally for a while, then gets obscured by the taskbar, and then every time I open the start menu after that, it gets obscured.

Your windows build is from July 9/2024: https://support.microsoft.com/en-au/topic/july-9-2024-kb5040442-os-builds-22621-3880-and-22631-3880-0864308e-61cc-413b-8194-0294331aba52

Please install the latest windows updates.

In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.

All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.

Preview updates are also not fully tested by Microsoft and thus could have bugs.

You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

**Comment by Wikeolf** [comment]
> Your windows build is from July 9/2024: https://support.microsoft.com/en-au/topic/july-9-2024-kb5040442-os-builds-22621-3880-and-22631-3880-0864308e-61cc-413b-8194-0294331aba52
> 
> Please install the latest windows updates.
> 
> In the settings app, untick "Get the latest updates as soon as available" so that preview updates are not automatically installed.
> 
> All preview updates are then shown as download and install and are never automatically installed if you have the above unticked.
> 
> Preview updates are also not fully tested by Microsoft and thus could have bugs.
> 
> You should only be installing preview updates if you are a developer or are OK with running pre-release versions of EP.

I've installed the latest windows update so far and the system version is now 23H2 22631.4169 but the problem still exists, the exact symptoms are the same as before the update.

**Comment by pyrates999** [comment]
Please wait for a developer to respond.
