### ISSUE TITLE
Windows 11 (build 10.0.22631.3593) - Windows 10 Start menu hangs for a bit before closing

### ISSUE THREAD

**Issue by win-ini** [valinet/ExplorerPatcher#3384]
https://github.com/valinet/ExplorerPatcher/assets/138562507/85b72b3c-9c4f-4ea7-bb1f-7c672b2ad45c

if I set this to Windows 11 style, the animation's a little glitchy with the task-bar on the top, but it doesn't hang before disappearing. I've seen this before with someone trying to revert Windows 11's UI changes back to Windows 10, if I remember correctly, but it's really noticeable and kind of bad, would really look forward to seeing this fixed.

edit: it possibly seems to be because I didn't register as a shell extention before?

**Comment by pyrates999** [comment]
I remember this was fixed in a previous release, but was flagged by antivirus, so it had to be removed.

**Comment by win-ini** [comment]
> I remember this was fixed in a previous release, but was flagged by antivirus, so it had to be removed.

weird. it's fixed itself after I registered it as a shell extention, maybe this is the reason?

**Comment by pyrates999** [comment]
Careful when enabling the option register as shell extension: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

**Comment by win-ini** [comment]
> Careful when enabling the option register as shell extension: https://github.com/valinet/ExplorerPatcher/wiki/Using-ExplorerPatcher-as-shell-extension

thanks! I've read through and, even after de-registering, it still doesn't hang. I don't know what caused it to hang then.

**Comment by Amrsatrio** [comment]
Did you restart Explorer after switching the start menu style?
