### ISSUE TITLE
Taskbar jump list flyout does not position correctly when the taskbar is not at the bottom

### ISSUE THREAD

**Issue by jw0785** [valinet/ExplorerPatcher#3515]
windows 11 22635.4000,
explorepatcher 22621.3880.66.3

It shows up in the opposite direction beyond the screen.

**Comment by Amrsatrio** [comment]
Duplicate of https://github.com/valinet/ExplorerPatcher/issues/3514

**Comment by jw0785** [comment]
I think it's not the same issue since the taskbar is fairly stable and doesn't crash.

I find the context menu will be consistently upward when the taskbar is set on the left, bottom, and right side. Further, if I place the taskbar on the top, and tick the auto hide, there will be a fragment of the context in the middle of the taskbar when right clicking.

**Comment by Amrsatrio** [comment]
I'll wait till the OP of that issue responds, and I am confident enough that it is the cause of the crash sometimes. If it is not, I'll close that issue as invalid and reopen this issue.

Meanwhile, you can try to disable ID 40874676 using vivetool to fix this issue for now.

**Comment by johnkarlhill** [comment]
I have this issue as well.
Windows Version 23H2 (22631.3958)
EP Version 22621.3880.66.3

**Comment by Amrsatrio** [comment]
Hold on guys. I'm brewing a patch for this which should be ready by tomorrow.

**Comment by Amrsatrio** [comment]
Fixed. A new prerelease build containing the fix is being built right now.

**Comment by derrapf** [comment]
I have currently the same issue.
Using EP 22621.3527.65.5  (by the way: Why can I not copy this version from the "about screen"?
My taskbar is on top. I have taskbar Tweaker installed; but still have the issue if I close taskbar Tweaker.

There is no right mouse-button context menu on the pinned applications in the taskbar

Is there any fix to that? I use EP because I want the taskbar on top of my screen

**Comment by pyrates999** [comment]
Please open a new issue for this as the original reason for this has been fixed.
