### ISSUE TITLE
Conflicts with TrafficMonitor, and the input method cannot be switched

### ISSUE THREAD

**Issue by zapplelove** [valinet/ExplorerPatcher#461]
before installed:
![image](https://user-images.githubusercontent.com/18183148/143176343-b87afab6-c331-48f3-8f7a-7c1cb56e99c0.png)
![image](https://user-images.githubusercontent.com/18183148/143176845-0aaeb34c-39f8-415b-956c-440abd17ef9d.png)

after installed:
![image](https://user-images.githubusercontent.com/18183148/143176470-145fa33c-ee12-4c2c-b1e2-ec7efee7ceb0.png)

**Comment by BraINstinct0** [comment]
First issue:

By TrafficMonitor I'll assume [this one], is it correct?
I am not 100 sure about what it does, so it'd be better if you could explain what it does, what is expected and what the current behavior's issue is.

Second issue:
The input method switcher is working well for me, so first try restarting then check if the issue persists.
Also for the input method switch not working, do you mean 'pressing Win+Spac'e doesn't switch it?

**Comment by BraINstinct0** [comment]
Edit: regarding the first issue, I'm pretty sure the issue is the widget not positioning properly.
Seems like a temporary workaround for it is to set `Taskbar Window Settings` > `Taskbar window` > `Taskbar window appears to the left of the taskbar` to selected.
That way you'll be able to see all info.
(will follow up if I come up with a proper solution)

**Comment by BraINstinct0** [comment]
A rather simple solution for the first issue seems, (un)ironically, to request a feature on TrafficMonitor's repo:
Giving it an option to offset the whole display by a specified(configurable) distance will let it fully display.

**Comment by zapplelove** [comment]
Thanks for your answer @BraINstinct0, TrafficMonitor is a software that can display CPU/Memory/Network usage in realtime. And this widget not positioning properly, if I do the `Taskbar Window Settings > Taskbar window > Taskbar window appears to the left of the taskbar`, it would be this:
![image](https://user-images.githubusercontent.com/18183148/143195217-b07b5cfd-5faf-4401-a678-9fc1f54c1371.png)
The second issue is solved by reinstead the language pack.

**Comment by zapplelove** [comment]
> A rather simple solution for the first issue seems, (un)ironically, to request a feature on TrafficMonitor's repo: Giving it an option to offset the whole display by a specified(configurable) distance will let it fully display.

Ok, I will reflect this problem in [that repo](https://github.com/zhongyang219/TrafficMonitor/)

**Comment by DigitalNXZ** [comment]
> before installed: ![image](https://user-images.githubusercontent.com/18183148/143176343-b87afab6-c331-48f3-8f7a-7c1cb56e99c0.png) ![image](https://user-images.githubusercontent.com/18183148/143176845-0aaeb34c-39f8-415b-956c-440abd17ef9d.png)
> 
> after installed: ![image](https://user-images.githubusercontent.com/18183148/143176470-145fa33c-ee12-4c2c-b1e2-ec7efee7ceb0.png)

It's more like a TrafficMonitor Issue (I think)~ 1.80.3 works absolute fine, while 1.8.1 (1.8.2 doesn't work at all) is always cut off like in ur Screenshot.

May try to downgrade if u still have this problem (I hope it gets fixed in a newer version of TrafficMonitor)~ ^^
